-- V1__create_users.sql
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(50),

    -- Audit fields (Spring Data JPA auditing)
    created_date TIMESTAMP,
    last_modified_date TIMESTAMP,
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),

    -- Discriminator column for SINGLE_TABLE inheritance
    type_users VARCHAR(31) NOT NULL DEFAULT 'USER'
);

-- Insert a default admin user
-- Password is "password" (BCrypt encoded)
INSERT INTO users (name, email, password, role, type_users, created_date, last_modified_date)
VALUES (
    'Admin User',
    'admin@example.com',
    '$2a$10$N9Zpww86/3S9.2SULeA25.2gCXYt.d7eR.j0pW4Lg2OSt.a7kU/eS',
    'ADMIN',
    'Admin',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);