-- V1__create_users.sql
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(50),

    -- Audit fields (Spring Data JPA auditing)
    created_date TIMESTAMP,
    last_modified_date TIMESTAMP,
    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),

    -- Discriminator column for SINGLE_TABLE inheritance
    type_users VARCHAR(31) NOT NULL DEFAULT 'USER'
);

-- Note: L'admin par défaut est créé par le CommandLineRunner dans GestionVisiteApplication.java
-- Cela garantit que le mot de passe est correctement hashé avec BCrypt
-- Email: admin@example.com
-- Password: admin123