-- V2__create_remaining_tables_postgres.sql

-- Table for statistiques
CREATE TABLE IF NOT EXISTS statistiques (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    periode DATE NOT NULL,
    nombre_visites INT NOT NULL,
    nombre_rdv INT NOT NULL,
    nombre_soumissions INT NOT NULL,
    duree_moyenne_minutes DOUBLE PRECISION
);
-- Only alter `users` if the table exists (prevents errors when migrations run out-of-order)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = 'users'
    ) THEN
        -- Alter users table (single-table inheritance fields)
        ALTER TABLE users ADD COLUMN IF NOT EXISTS type_users VARCHAR(31) NOT NULL DEFAULT 'USER';

        -- Admin fields
        ALTER TABLE users ADD COLUMN IF NOT EXISTS privileges VARCHAR(255);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS statistique_id BIGINT;

        -- Add FK users.statistique_id -> statistiques.id (if not exists)
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_statistique') THEN
            ALTER TABLE users ADD CONSTRAINT fk_users_statistique FOREIGN KEY (statistique_id) REFERENCES statistiques(id);
        END IF;

        -- AgentSecurite field
        ALTER TABLE users ADD COLUMN IF NOT EXISTS matricule VARCHAR(255);

        -- Employe field
        ALTER TABLE users ADD COLUMN IF NOT EXISTS secteur_activite VARCHAR(255);

        -- Secretaire field
        ALTER TABLE users ADD COLUMN IF NOT EXISTS departement VARCHAR(255);

        -- Visiteur fields
        ALTER TABLE users ADD COLUMN IF NOT EXISTS entreprise VARCHAR(255);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS scan_document_path VARCHAR(255);
        ALTER TABLE users ADD COLUMN IF NOT EXISTS signature_path VARCHAR(255);
    END IF;
END$$;

-- Table for visites
CREATE TABLE IF NOT EXISTS visites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visite_date TIMESTAMP NOT NULL,
    h_entree TIMESTAMP,
    h_sortie TIMESTAMP,
    motif VARCHAR(255) NOT NULL,
    statut VARCHAR(255) NOT NULL,
    employe_id BIGINT,
    agent_securite_id BIGINT,
    statistique_id BIGINT
);

-- Foreign keys for visites (create if not exists)
DO $$
BEGIN
    -- add user-related FKs only if users table exists
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'users') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visites_employe') THEN
            ALTER TABLE visites ADD CONSTRAINT fk_visites_employe FOREIGN KEY (employe_id) REFERENCES users(id);
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visites_agent_securite') THEN
            ALTER TABLE visites ADD CONSTRAINT fk_visites_agent_securite FOREIGN KEY (agent_securite_id) REFERENCES users(id);
        END IF;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_visites_statistique') THEN
        ALTER TABLE visites ADD CONSTRAINT fk_visites_statistique FOREIGN KEY (statistique_id) REFERENCES statistiques(id);
    END IF;
END$$;

-- Table for notifications
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR(255),
    notification_date DATE,
    statut BOOLEAN,
    visite_id BIGINT
);

-- FK for notifications
DO $$
BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_notifications_visite') THEN
    ALTER TABLE notifications ADD CONSTRAINT fk_notifications_visite FOREIGN KEY (visite_id) REFERENCES visites(id);
END IF;
END$$;

-- Table for rendez_vous
CREATE TABLE IF NOT EXISTS rendez_vous (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rdv_date DATE NOT NULL,
    rdv_heure TIME NOT NULL,
    type_rdv VARCHAR(255),
    statut BOOLEAN,
    code VARCHAR(255) UNIQUE,
    visite_id BIGINT,
    statistique_id BIGINT,
    secretaire_id BIGINT
);

-- FKs for rendez_vous
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rdv_visite') THEN
    ALTER TABLE rendez_vous ADD CONSTRAINT fk_rdv_visite FOREIGN KEY (visite_id) REFERENCES visites(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rdv_statistique') THEN
        ALTER TABLE rendez_vous ADD CONSTRAINT fk_rdv_statistique FOREIGN KEY (statistique_id) REFERENCES statistiques(id);
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'users') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_rdv_secretaire') THEN
            ALTER TABLE rendez_vous ADD CONSTRAINT fk_rdv_secretaire FOREIGN KEY (secretaire_id) REFERENCES users(id);
        END IF;
    END IF;
END$$;

-- Table for soumission_rdv
CREATE TABLE IF NOT EXISTS soumission_rdv (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL,
    departement VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telephone VARCHAR(255) NOT NULL,
    entreprise VARCHAR(255) NOT NULL,
    motif VARCHAR(255) NOT NULL,
    date_rendezvous DATE NOT NULL,
    heure_rendezvous TIME NOT NULL,
    statut VARCHAR(255) NOT NULL,
    rendezvous_id BIGINT UNIQUE,
    visiteur_id BIGINT
);

-- FKs for soumission_rdv
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_soumissionrdv_rdv') THEN
        ALTER TABLE soumission_rdv ADD CONSTRAINT fk_soumissionrdv_rdv FOREIGN KEY (rendezvous_id) REFERENCES rendez_vous(id);
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'users') THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_soumissionrdv_visiteur') THEN
            ALTER TABLE soumission_rdv ADD CONSTRAINT fk_soumissionrdv_visiteur FOREIGN KEY (visiteur_id) REFERENCES users(id);
        END IF;
    END IF;
END$$;
